# Generated by Django 5.1.4 on 2025-03-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='pics',
        ),
    ]
